### PR TITLE
Documentation for the YAML input

### LINKED ISSUE #50: Specification for the YAML format
I'm currently playing around with the YAML input and would like to know whether there is a specification or documentation for the expected format. The examples are very different in their structure. What is the best resource in general to get to know Carneades and it's capabilities?

### PR DESCRIPTION
**Pull request by mgttlinger**
As discussed I took a stab at documenting the YAML input.

fixes #50

### CODE REVIEW

**Comment by mgttlinger** [comment]
Also: I'm currently participating in Hacktoberfest (https://hacktoberfest.com/). If you think this PR is a valuable contribution, could you label this PR `hacktoberfest-accepted` so it counts towards my open-source contributions.

**Comment by tfgordon** [comment]
Thanks for doing this. I really appreciate it. I'll get back to you
soon
with any comments or suggestions I may have.

Tom

---
Tom Gordon
***@***.***

On 2024-10-09 10:51, Merlin wrote: 

> As discussed I took a stab at documenting the YAML input. 
> 
> fixes #50 [1] 
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
> https://github.com/carneades/carneades-4/pull/52 [2] 
> 
> COMMIT SUMMARY
> 
> * 1ccad6d [3] Documentation for the YAML input
> 
> FILE CHANGES
> 
> (1 file [4]) 
> 
> * A USAGE.md [5] (114)
> 
> PATCH LINKS:
> 
> * https://github.com/carneades/carneades-4/pull/52.patch [6]
> * https://github.com/carneades/carneades-4/pull/52.diff [7]
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [8].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/carneades/carneades-4/issues/50
[2] https://github.com/carneades/carneades-4/pull/52
[3]
https://github.com/carneades/carneades-4/pull/52/commits/1ccad6d7fa4db015ff1bd57a2c941ea6b7f68a43
[4] https://github.com/carneades/carneades-4/pull/52/files
[5]
https://github.com/carneades/carneades-4/pull/52/files#diff-58a825c70bccfbe691d7ddbddb133275f4f657de6aeb4a502fa9fce279f8bf8d
[6] https://github.com/carneades/carneades-4/pull/52.patch
[7] https://github.com/carneades/carneades-4/pull/52.diff
[8]

**Review by tfgordon — APPROVED** [review]
Thanks again for writing this documentation, which I'm sure will be helpful for potential users.

**Comment by tfgordon** [comment]
Dear Merlin,

I corrected a few spelling errors, added the requested label to your
merge request and confirmed 
the merge. 

Thanks again!

Tom

---
Tom Gordon
***@***.***

On 2024-10-09 10:51, Merlin wrote: 

> As discussed I took a stab at documenting the YAML input. 
> 
> fixes #50 [1] 
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
> https://github.com/carneades/carneades-4/pull/52 [2] 
> 
> COMMIT SUMMARY
> 
> * 1ccad6d [3] Documentation for the YAML input
> 
> FILE CHANGES
> 
> (1 file [4]) 
> 
> * A USAGE.md [5] (114)
> 
> PATCH LINKS:
> 
> * https://github.com/carneades/carneades-4/pull/52.patch [6]
> * https://github.com/carneades/carneades-4/pull/52.diff [7]
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [8].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/carneades/carneades-4/issues/50
[2] https://github.com/carneades/carneades-4/pull/52
[3]
https://github.com/carneades/carneades-4/pull/52/commits/1ccad6d7fa4db015ff1bd57a2c941ea6b7f68a43
[4] https://github.com/carneades/carneades-4/pull/52/files
[5]
https://github.com/carneades/carneades-4/pull/52/files#diff-58a825c70bccfbe691d7ddbddb133275f4f657de6aeb4a502fa9fce279f8bf8d
[6] https://github.com/carneades/carneades-4/pull/52.patch
[7] https://github.com/carneades/carneades-4/pull/52.diff
[8]

**Comment by mgttlinger** [comment]
Awesome. Glad I could help!

**Pull request merged**
